<?php

//reports.php - controller
$lang['reports_generating'] = "Generating report";
$lang['reports_err_generating'] = "Could not generate report";
$lang['reports_success_removed'] = "Report removed successfully!";
$lang['reports_success_removed_all'] = "All Reports removed successfully!";
$lang['reports_confirm_all_files_remove'] = "Do you really want to delete all reports?";
$lang['reports_file_not_search'] = "There are no reviews for this product.";
$lang['reports_queue_success_remove'] = "Report removed of the queue successfully!";
$lang['reports_queue_error_remove'] = "Could not to remove the report of the queue!";
$lang['reports_provide_interv_from'] = "You must provide a Interval (From)";
$lang['reports_provide_interv_until'] = "You must provide a Interval (Until)";

//reports.php - view
$lang['reports_header'] = "Reports";
$lang['reports_pre_title'] = "Reports";
$lang['reports_title_sub1'] = "Summarized";
$lang['reports_title_sub2'] = "Detailed";
$lang['reports_input_filters'] = "Filters";
$lang['reports_input_period'] = "Period";
$lang['reports_input_registers'] = "Total records";
$lang['reports_input_ext'] = "Format";
$lang['reports_btn_process'] = "Process";
$lang['reports_btn_loading'] = "Loading ...";
$lang['reports_custom_title'] = "Data Export";
$lang['reports_input_interval'] = "Range";
$lang['reports_input_from'] = "From:";
$lang['reports_input_until'] = "To:";
$lang['reports_input_user'] = "User";
$lang['reports_input_ip'] = "IP";
$lang['reports_input_categories'] = "Categories";
$lang['reports_input_total_records'] = "Total Records";
$lang['reports_msg_limit'] = "The interval limit for 3 months query!";
$lang['reports_msg_select_rel'] = "Select Report!";
$lang['reports_zone'] = "Zone";
$lang['report_check_processing'] = "Generating Reports";
$lang['report_title_exports'] = "List of empty data export reports:";

//reporta_files.php
$lang['reports_files_header'] = "Report List";
$lang['reports_files_date'] = "Date / Time";
$lang['reports_files_report'] = "Report";
$lang['reports_files_download'] = "Download";
$lang['reports_files_remove'] = "Remove File";
$lang['reports_all_files_remove'] = "Remove All Files";
$lang['reports_files_processing'] = "Processing";
$lang['reports_files_filesize'] = "Size (bytes)";

//reports_helper.php
$lang['reports_helpers_prel1'] = "TOP Users (MB Consumption)";
$lang['reports_helpers_prel2'] = "TOP Social Networks (Hits)";
$lang['reports_helpers_prel3'] = "TOP Categories (Hits)";
$lang['reports_helpers_prel4'] = "TOP Domains (MB Consumption)";
$lang['reports_helpers_prel5'] = "TOP Sites";
$lang['reports_helpers_prel6'] = "TOP VPN Users (Connection Time)";
$lang['reports_helpers_prel7'] = "Facebook Access TOPs";
$lang['reports_helpers_prel8'] = "TOP Youtube Access";
$lang['reports_helpers_prel9'] = "TOP Access Instagram";
$lang['reports_helpers_prel10'] = "TOP Accesses Linkedin";
$lang['reports_helpers_crel1'] = "User Access";
$lang['reports_helpers_crel2'] = "Access by IP Address";
$lang['reports_helpers_crel3'] = "VPN connection time";
$lang['reports_helpers_crel4'] = "Captive Portal/Audit";
$lang['reports_helpers_crel5'] = "Top Accessed Domains";
$lang['reports_helpers_crel6'] = "WebFilter Justifications";
$lang['reports_helpers_crel7'] = "Detailed VPN Connection Time";
$lang['reports_helpers_crel8'] = "UTM activity newsletter";
$lang['reports_helpers_erel1'] = "User Access (Analytic)";
$lang['reports_helpers_erel2'] = "IP Address Access (Analytical)";
$lang['reports_helpers_erel3'] = "Access per Users Group";
$lang['reports_helpers_recent'] = "Recent";
$lang['reports_helpers_7days'] = "7 days";
$lang['reports_helpers_30days'] = "30 days";

//ReportsCommandLine.php
$lang['reports_cmd_err1'] = "Could not execute command:";
$lang['reports_cmd_err2'] = "The process PID could not be set!";
$lang['reports_cmd_err3'] = "Could not create process PID!";
$lang['reports_cmd_err4'] = "Could not get report data!";
$lang['reports_cmd_footer'] = "Generated by BluePex DataClick | {PAGENO} of {nb}";
$lang['reports_cmd_consumer'] = "Total Consumed (MB)";
$lang['reports_cmd_access'] = "Total Accessed";
$lang['reports_cmd_categ'] = "Categories";
$lang['reports_cmd_ip'] = "IP Address";
$lang['reports_cmd_username'] = "Username";
$lang['reports_cmd_session'] = "Session";
$lang['reports_cmd_zone'] = "Zone";
$lang['reports_cmd_mac'] = "MAC Address";
$lang['reports_cmd_beg_connect'] = "Connection Started In";
$lang['reports_cmd_last_active'] = "Last Activity";
$lang['reports_cmd_disp'] = "Device";
$lang['reports_cmd_rem_ip'] = "Remote IP Address";
$lang['reports_cmd_domain'] = "Domain";
$lang['reports_cmd_connect_time'] = "Connection Time";
$lang['reports_cmd_port'] = "Port";
$lang['reports_cmd_bytes_send'] = "Bytes Sent";
$lang['reports_cmd_bytes_rec'] = "Bytes Received";
$lang['reports_cmd_yes'] = "Yes";
$lang['reports_cmd_no'] = "No";
$lang['reports_cmd_blocked'] = "Locked";
$lang['reports_cmd_local_ip'] = "Local IP Address";
$lang['reports_cmd_group'] = "Group";
$lang['reports_cmd_date'] = "Date / Time";
$lang['reports_cmd_default_utm'] = "The UTM pattern does not exist!";
$lang['reports_cmd_time_connect'] = "Connection";
$lang['reports_cmd_time_disconnect'] = "Disconnection";
$lang['reports_cmd_text_title_inputs_block'] = "Select a report type to enable the fields";
$lang['reports_cmd_text_title_inputs_block_user'] = "Field blocked for reasons that a user type report is selected, change the reports to release the field again";
$lang['reports_cmd_text_title_inputs_block_group'] = "Field blocked for reasons that a group type report is selected, change the reports to release the field again";
$lang['reports_cmd_text_title_inputs_block_ip'] = "Field blocked for reasons that an IP type report is selected, change the reports to release the field again";
$lang['reports_cmd_descr'] = "Description";

//000x.php
$lang['reports_c_period'] = "Period (of):";
$lang['reports_c_period_until'] = "Period (to):";
$lang['reports_c_user'] = "User:";
$lang['reports_c_ip'] = "IP:";
$lang['reports_c_address'] = "Address:";
$lang['reports_c_user'] = "User";
$lang['reports_c_session'] = "Session";
$lang['reports_c_group'] = "Group / Cost Center";
$lang['reports_c_access'] = "Access Qty";
$lang['reports_c_consumer'] = "Consumption (MB)";
$lang['reports_c_totalmb'] = "Total (MB):";
$lang['reports_c_date'] = "Date / Time";
$lang['reports_c_categ'] = "Categories";
$lang['reports_c_access_time'] = "Access time (sec)";
$lang['reports_c_remote_ip'] = "IP Remote";
$lang['reports_c_local_ip'] = "Local IP";
$lang['reports_c_port'] = "Port";
$lang['reports_c_bytes_send'] = "Sent Data (bytes)";
$lang['reports_c_bytes_rec'] = "Data Received (bytes)";
$lang['reports_c_temp'] = "time";
$lang['reports_c_mac'] = "MAC Address";
$lang['reports_c_begin_activities'] = "Connection Started In";
$lang['reports_c_last_activities'] = "Last Activity";
$lang['reports_c_disp'] = "Device";
$lang['reports_c_rejected'] = "Rejected";
$lang['reports_c_justification'] = "Justification";
$lang['reports_c_source'] = "Source";
$lang['reports_c_name'] = "Name";
$lang['reports_c_last_name'] = "Last Name";
$lang['reports_c_birthday'] = "Birthday";
$lang['reports_c_form1'] = "Form 1";
$lang['reports_c_form2'] = "Form 2";
$lang['reports_c_time_connect'] = "Connection";
$lang['reports_c_time_disconnect'] = "Disconnection";
$lang['reports_c_descr'] = "Description";

//P000x.php
$lang['reports_p_period'] = "Period (of):";
$lang['reports_p_interval_of'] = "Range (of):";
$lang['reports_p_interval_until'] = "Range (to):";
$lang['reports_p_utm'] = "UTM:";
$lang['reports_p_address'] = "Address:";
$lang['reports_p_user'] = "User";
$lang['reports_p_consumer'] = "Consumption (MB)";
$lang['reports_p_access'] = "Access Qty";
$lang['reports_p_domain'] = "Domain";
$lang['reports_p_consumer'] = "Consumption (MB)";
$lang['reports_p_totalmb'] = "Total (MB):";
$lang['reports_p_connect_time'] = "Connection time (ms)";
$lang['reports_p_ip'] = "IP Address:";

//Report 0008
$lang['report_0008_acp_fapp'] = '%1$s: Added interface: \'%2$s\'';

$lang['report_0008_session_logout'] = 'Session: Logout';
$lang['report_0008_session_login'] = 'Session: Login';

$lang['report_0008_firewall_obj_delete'] = 'Firewall objects: Deleted object \'%1$s\'';
$lang['report_0008_firewall_obj_edit'] = 'Firewall objects: Edited alias \'%1$s\'';
$lang['report_0008_firewall_obj_new'] = 'Firewall objects: New alias \'%1$s\'';
$lang['report_0008_firewall_obj_dup'] = 'Firewall objects: Duplicate alias \'%1$s\' for \'%2$s\'';
$lang['report_0008_firewall_obj_reload_filter'] = 'Firewall objects: Firewall rules filter reloaded';

$lang['report_0008_firewall_nat_1to1_filter_reload'] = 'Firewall Rules Nat 1to1: Firewall rules filter reloaded';
$lang['report_0008_firewall_nat_1to1_filter_reordered'] = 'Firewall Rules Nat 1to1: Reordered firewall rules';
$lang['report_0008_firewall_nat_1to1_filter_toggle_enabled'] = 'Firewall Rules Nat 1to1: Rule \'%1$s (%2$s)\' enabled';
$lang['report_0008_firewall_nat_1to1_filter_toggle_disabled'] = 'Firewall Rules Nat 1to1: Rule \'%1$s (%2$s)\' disabled';
$lang['report_0008_firewall_nat_1to1_filter_delete'] = 'Firewall Rules Nat 1to1: Rule \'%1$s (%2$s)\' deleted ';

$lang['report_0008_firewall_nat_ports_filter_reload'] = 'Firewall Rules Nat NTP: Firewall rules filter reloaded';
$lang['report_0008_firewall_nat_ports_filter_reordered'] = 'Firewall Rules Nat NTP: Nat firewall rules reordered';
$lang['report_0008_firewall_nat_ports_filter_toggle_enabled'] = 'Firewall Rules Nat NTP: Rule \'%1$s (%2$s / %3$s)\' enabled';
$lang['report_0008_firewall_nat_ports_filter_toggle_disabled'] = 'Firewall Rules Nat NTP: Rule \'%1$s (%2$s / %3$s)\' disabled';
$lang['report_0008_firewall_nat_ports_filter_delete'] = 'Firewall Rules Nat NTP: Rule \'%1$s (%2$s / %3$s)\' deleted';

$lang['report_0008_firewall_nat_ports_filter_reload'] = 'Firewall Rules Nat Ports: Reload filter';
$lang['report_0008_firewall_nat_ports_filter_reordered'] = 'Firewall Rules Nat Ports: reordered firewall rules';
$lang['report_0008_firewall_nat_ports_filter_toggle_enabled'] = 'Firewall Rules Nat Ports: Rule \'%1$s (%2$s)\' enabled';
$lang['report_0008_firewall_nat_ports_filter_toggle_disabled'] = 'Firewall Rules Nat Ports: Rule \'%1$s (%2$s)\' disabled';
$lang['report_0008_firewall_nat_ports_filter_delete'] = 'Firewall Rules Nat Ports: Rule \'%1$s (%2$s)\' deleted';

$lang['report_0008_acp_fapp_stream'] = '%1$s: Stream interfaces/memory limit stream: \'%2$s (%3$s)\'';
$lang['report_0008_acp_fapp_edit'] = '%1$s: Edited interface: \'%2$s (%3$s)\'';
$lang['report_0008_acp_fapp_dup'] = '%1$s: Duplicate interface: \'%2$s (%3$s)\' to \'%4$s (%5$s)\'';
$lang['report_0008_acp_fapp_enabled'] = '%1$s: Interface enabled: \'%2$s (%3$s)\'';
$lang['report_0008_acp_fapp_disabled'] = '%1$s: interface disabled: \'%2$s (%3$s)\'';
$lang['report_0008_acp_fapp_removed'] = '%1$s: interface removed: \'%2$s (%3$s)\'';
$lang['report_0008_acp_fapp_start'] = '%1$s: Start interface: \'%2$s (%3$s)\'';
$lang['report_0008_acp_fapp_restart'] = ' %1$s: Restart interface: \'%2$s (%3$s)\'';
$lang['report_0008_acp_fapp_stop'] = '%1$s: Interface stopped: \'%2$s (%3$s)\'';
$lang['report_0008_acp_fapp_gtw_fapp_to_acp'] = 'Active Protection: Interface converted from FirewallApp: \'%1$s\'';
$lang['report_0008_acp_fapp_gtw_acp_to_fapp'] = 'FirewallApp: Interface converted from Active Protection: \'%1$s\'';
$lang['report_0008_acp_fapp_no_gtw_fapp_to_acp'] = 'Active Protection: Interface converted to FirewallApp: \'%1$s\'';
$lang['report_0008_acp_fapp_no_gtw_acp_to_fapp'] = 'FirewallApp: Interface converted to Active Protection: \'%1$s\'';

$lang['report_0008_webfilter_setting_new'] = 'Webfilter: New instance configuration \'%1$s\'';
$lang['report_0008_webfilter_setting_edit'] = 'Webfilter: Edited instance configuration \'%1$s\'';
$lang['report_0008_webfilter_setting_remove'] = 'Webfilter: Removed instance configuration \'%1$s\'';

$lang['report_0008_webfilter_server_new'] = 'Webfilter: New proxy server configuration \'%1$s\'';
$lang['report_0008_webfilter_server_edit'] = 'Webfilter: Edited proxy server configuration \'%1$s\'';

$lang['report_0008_webfilter_server_remove'] = 'Webfilter: Deleted proxy server \'%1$s\'';
$lang['report_0008_webfilter_server_reorder'] = 'Webfilter: Reordered proxy servers';

$lang['report_0008_openvpn_wizard_new'] = 'OpenVPN: New server \'%1$s (%2$s)\'';

$lang['report_0008_firewall_nat_1to1_filter_edit'] = 'Firewall Rules Nat 1to1: Edited Rule \'%1$s (%2$s)\'';
$lang['report_0008_firewall_nat_1to1_filter_new'] = 'Firewall Rules Nat 1to1: New Rule \'%1$s (%2$s)\'';
$lang['report_0008_firewall_nat_1to1_filter_dup'] = 'Firewall Rules Nat 1to1: Duplicate Rule \'%1$s (%2$s)\' for \'%3$s (%4$s)\'';

$lang['report_0008_firewall_nat_ports_filter_edit'] = 'Firewall Rules Nat Ports: Edited Rule \'%1$s (%2$s / %3$s)\'';
$lang['report_0008_firewall_nat_ports_filter_new'] = 'Firewall Rules Nat Ports: New Rule \'%1$s (%2$s / %3$s)\'';
$lang['report_0008_firewall_nat_ports_filter_dup'] = 'Firewall Rules Nat Ports: Duplicate Rule \'%1$s (%2$s / %3$s)\' for \'%4$s (%5$s / %6$s)\'';

$lang['report_0008_firewall_nat_ntp_filter_edit'] = 'Firewall Rules Nat NTP: Edited Rule \'%1$s (%2$s)\'';
$lang['report_0008_firewall_nat_ntp_filter_new'] = 'Firewall Rules Nat NTP: New Rule \'%1$s (%2$s)\'';
$lang['report_0008_firewall_nat_ntp_filter_dup'] = 'Firewall Rules Nat NTP: Duplicate Rule \'%1$s (%2$s)\' for \'%3$s (%4$s)\'';

$lang['report_0008_firewall_nat_outbound_filter_mode'] = 'Firewall Rules Nat Outbound: Outbound Nat Mode set to \'%1$s\'';

$lang['report_0008_firewall_nat_outbound_filter_edit'] = 'Firewall Rules Nat Outbound: Edited Rule \'%1$s (%2$s)\'';
$lang['report_0008_firewall_nat_outbound_filter_new'] = 'Firewall Rules Nat Outbound: New Rule \'%1$s (%2$s)\'';
$lang['report_0008_firewall_nat_outbound_filter_dup'] = 'Firewall Rules Nat Outbound: Duplicate Rule \'%1$s (%2$s)\' for \'%3$s (%4$s)\'';

$lang['report_0008_firewall_nat_outbound_filter_reordered'] = "Firewall Rules Nat Outbound: Firewall rules reordered";
$lang['report_0008_firewall_nat_outbound_filter_reload_filter'] = "Firewall Rules Nat Outbound: Firewall rules filter reloaded";
$lang['report_0008_firewall_nat_outbound_filter_delete'] = 'Firewall Rules Nat Outbound: Rule \'%1$s (%2$s)\' deleted';
$lang['report_0008_firewall_nat_outbound_filter_enabled'] = 'Firewall Rules Nat Outbound: Rule \'%1$s (%2$s)\' enabled';
$lang['report_0008_firewall_nat_outbound_filter_disabled'] = 'Firewall Rules Nat Outbound: Rule \'%1$s (%2$s)\' disabled';

$lang['report_0008_firewall_rules_rename'] = 'Firewall Rules: Renamed rule \'%1$s (%2$s / %3$s)\' to \'%4$s (%5$s / %6$s)\'';
$lang['report_0008_firewall_rules_edit'] = 'Firewall Rules: Edited Rule \'%1$s (%2$s / %3$s)\'';
$lang['report_0008_firewall_rules_new'] = 'Firewall Rules: New Rule \'%1$s (%2$s / %3$s)\'';
$lang['report_0008_firewall_rules_dup'] = 'Firewall Rules: Duplicate Rule \'%1$s (%2$s / %3$s)\' for \'%4$s (%5$s / %6$s)\'';

$lang['report_0008_firewall_rules_reload_filter'] = 'Firewall Rules: Firewall rules filter reloaded';
$lang['report_0008_firewall_rules_delete'] = 'Firewall Rules: Rule \'%1$s (%2$s / %3$s)\' deleted';
$lang['report_0008_firewall_rules_killed'] = 'Firewall Rules: Filter process \'%1$s (%2$s / %3$s)\' has been killed';
$lang['report_0008_firewall_rules_enabled'] = 'Firewall Rules: Rule \'%1$s (%2$s / %3$s)\' enabled';
$lang['report_0008_firewall_rules_disabled'] = 'Firewall Rules: Rule \'%1$s (%2$s / %3$s)\' disabled';
$lang['report_0008_firewall_rules_reordered'] = 'Firewall Rules: Reordered firewall rules';
$lang['report_0008_firewall_rules_copy'] = 'Firewall Rules: Duplicate Rule \'%1$s (%2$s / %3$s)\' for \'%4$s (%5$s / %6$ s)\'';

$lang['report_0008_interface_assign_new'] = 'Control Interfaces: Add new interface: \'%1$s (%2$s)\'';
$lang['report_0008_interface_assign_remove'] = 'Control Interfaces: Remove interface: \'%1$s (%2$s)\'';
$lang['report_0008_interface_assign_reload_filter'] = "Control Interfaces: Firewall rules filter reloaded";
$lang['report_0008_interface_assign_enabled'] = 'Control Interfaces: Enable interface: \'%1$s (%2$s)\'';
$lang['report_0008_interface_assign_disabled'] = 'Control Interfaces: Disabled interface: \'%1$s (%2$s)\'';
$lang['report_0008_interface_assign_edit'] = 'Control Interfaces: Edited interface: \'%1$s (%2$s)\'';

$lang['report_0008_captiveportal_zone_added_filemanager'] = 'Captive Portal File Manager: Add file \'%1$s\' to zone \'%2$s\'';
$lang['report_0008_captiveportal_zone_delete_filemanager'] = 'Captive Portal File Manager: Delete file \'%1$s\' to zone \'%2$s\'';

$lang['report_0008_captiveportal_zone_high_avaiabled_enabled'] = 'Captive Portal High Avaliabled: Enable condition to zone \'%1$s\'';
$lang['report_0008_captiveportal_zone_high_avaiabled_disabled'] = 'Captive Portal High Avaliabled: Disabled condition to zone \'%1$s\'';
$lang['report_0008_captiveportal_zone_high_avaiabled_edit'] = 'Captive Portal High Avaliabled: Edited of the zone \'%1$s\'';

$lang['report_0008_captiveportal_zone_hostname_edit'] = 'Captive Portal Hostname Rules: Edited Rule \'%1$s\' of zone \'%2$s\'';
$lang['report_0008_captiveportal_zone_hostname_new'] = 'Captive Portal Hostname Rules: New Rule \'%1$s\' of zone \'%2$s\'';
$lang['report_0008_captiveportal_zone_hostname_del'] = 'Captive Portal Hostname Rules: Delete Rule \'%1$s\' of zone \'%2$s\'';

$lang['report_0008_captiveportal_ip_edit'] = 'Captive Portal Ip Rules: Edited Rule \'%1$s\' of zone \'%2$s\'';
$lang['report_0008_captiveportal_ip_new'] = 'Captive Portal Ip Rules: New Rule \'%1$s\' of zone \'%2$s\'';
$lang['report_0008_captiveportal_ip_del'] = 'Captive Portal Ip Rules: Delete Rule \'%1$s\' of zone \'%2$s\'';

$lang['report_0008_captiveportal_mac_edit'] = 'Captive Portal Mac Rules: Edited Rule \'%1$s\' of zone \'%2$s\'';
$lang['report_0008_captiveportal_mac_new'] = 'Captive Portal Mac Rules: New Rule \'%1$s\' of zone \'%2$s\'';
$lang['report_0008_captiveportal_mac_del'] = 'Captive Portal Mac Rules: Delete Rule \'%1$s\' of zone \'%2$s\'';

$lang['report_0008_captiveportal_control_user_changed'] = 'Captive Portal Control User: Changed password for user \'%1$s\' and logged outof zone \'%2$s\'';
$lang['report_0008_captiveportal_control_user_applied'] = 'Captive Portal Control User: Applied quarantine actions to captive users of zone \'%1$s\'';
$lang['report_0008_captiveportal_control_user_deleted'] = 'Captive Portal Control User: Delete user \'%1$s\' and logged outof zone \'%2$s\'';

$lang['report_0008_captiveportal_voucher_edit'] = 'Captive Portal Vouchers: Edited list vouchers \'%1$s\' to login of zone \'%2$s\'';
$lang['report_0008_captiveportal_voucher_new'] = 'Captive Portal Vouchers: New list vouchers \'%1$s\' to login of zone \'%2$s\'';
$lang['report_0008_captiveportal_voucher_del'] = 'Captive Portal Vouchers: Delete list \'%1$s\' of zone \'%2$s\'';
$lang['report_0008_captiveportal_voucher_enabled'] = 'Captive Portal Vouchers: Enabled vouchers to login of zone \'%1$s\'';
$lang['report_0008_captiveportal_voucher_disabled'] = 'Captive Portal Vouchers: Disabled vouchers to login of zone \'%1$s\'';
$lang['report_0008_captiveportal_voucher_edit_voucher'] = 'Captive Portal Vouchers: Edited vouchers to login of zone \'%1$s\'';

$lang['report_0008_captiveportal_zone_added'] = 'Captive Portal: Add new zone \'%1$s\'';
$lang['report_0008_captiveportal_zone_remove'] = 'Captive Portal: Remove instance \'%1$s\'';

$lang['report_0008_captiveportal_edit'] = 'Captive Portal: Edited zone \'%1$s\'';
$lang['report_0008_captiveportal_enabled'] = 'Captive Portal: Enabled zone \'%1$s\'';
$lang['report_0008_captiveportal_disabled'] = 'Captive Portal: Disabled zone \'%1$s\'';

$lang['report_0008_service_dhcp_edit'] = 'Service DHCP: Edited mapping \'%1$s (%2$s)\' to server static DHCP in \'%3$s (%4$s)\'';
$lang['report_0008_service_dhcp_new'] = 'Service DHCP: New mapping \'%1$s (%2$s)\' to server static DHCP in \'%3$s (%4$s)\'';
$lang['report_0008_service_dhcp_enabled'] = 'Service DHCP: Enable service in interface \'%1$s (%2$s)\'';
$lang['report_0008_service_dhcp_disabled'] = 'Service DHCP: Disabled service in interface \'%1$s (%2$s)\'';

$lang['report_0008_service_dhcp_pool_edit'] = 'Service DHCP: Edited pool DHCP \'%1$s\' in interface \'%2$s (%3$s)\'';
$lang['report_0008_service_dhcp_pool_new'] = 'Service DHCP: Add new pool DHCP \'%1$s\' in interface \'%2$s (%3$s)\'';
$lang['report_0008_service_dhcp_pool_edit_service'] = 'Service DHCP: Edited service in interface \'%1$s (%2$s)\'';
$lang['report_0008_service_dhcp_reload_filter'] = 'Service DHCP: Firewall rules filter reloaded';
$lang['report_0008_service_dhcp_pool_delete'] = 'Service DHCP: Delete server pool DHCP \'%1$s\' in interface \'%2$s (%3$s)\'';
$lang['report_0008_service_dhcp_mapping_delete'] = 'Service DHCP: Delete mapping to server static DHCP \'%1$s (%2$s)\' in interface \'%3$s (%4$s)\'';

$lang['report_0008_services_db_update'] = 'Bluepex Services: Updated process status';
$lang['report_0008_services_db_create'] = 'Bluepex Services: Process management created';
$lang['report_0008_services_db_add'] = 'Bluepex Services: Added new process to management';

$lang['report_0008_filter_status_filter_reload'] = 'Firewall Status: Firewall rule filter reloaded';
$lang['report_0008_filter_status_sync'] = 'Firewall Status: Sync filter';

$lang['report_0008_services_internal_restart'] = 'Internal Service: \'%1$s\' being restarted';
$lang['report_0008_services_internal_start'] = 'Internal Service: \'%1$s\' being started';
$lang['report_0008_services_internal_stop'] = 'Internal Service: \'%1$s\' being stopped';

$lang['report_0008_system_auth_dup'] = 'Remote Connection LDAP/Radius: Duplicate authentication \'%1$s\' for \'%2$s (%3$s)\'';
$lang['report_0008_system_auth_edit'] = 'Remote Connection LDAP/Radius: Edited authentication \'%1$s (%2$s)\'';
$lang['report_0008_system_auth_new'] = 'Remote Connection LDAP/Radius: New authentication \'%1$s (%2$s)\'';
$lang['report_0008_system_auth_del'] = 'Remote Connection LDAP/Radius: Delete authentication with \'%1$s (%2$s)\'';

$lang['report_0008_system_auth_connection_no_first_authentication_method'] = 'LDAP/Radius remote connection: Added authentication method \'%1$s\'';
$lang['report_0008_system_auth_connection'] = 'LDAP/Radius remote connection: Authentication method changed from \'%1$s\' to \'%2$s\'';

$lang['report_0008_system_user_del'] = 'Control User: Removed user/s: \'%1$s\'';
$lang['report_0008_system_user_added_cert'] = 'User control: Certificate added \'%1$s\' for user \'%2$s\'';
$lang['report_0008_system_user_remove_cert'] = 'Control User: Removed certificate \'%1$s\' from user \'%2$s\'';
$lang['report_0008_system_user_added_priv'] = 'User control: Added privilege \'%1$s\' for user \'%2$s\'';
$lang['report_0008_system_user_remove_priv'] = 'Control User: Removed privilege \'%1$s\' from user \'%2$s\'';
$lang['report_0008_system_user_remove_edited'] = 'Control User: Successfully edited user \'%1$s\'';
$lang['report_0008_system_user_remove_created'] = 'Control User: Successfully created user \'%1$s\'';
$lang['report_0008_system_user_renewed_pass'] = 'Control User: Password renewed in user \'%1$s\'';

$lang['report_0008_system_import_sync_enabled'] = 'Remote Connection LDAP/Radius: Enabled synchronization with LDAP';
$lang['report_0008_system_import_sync_edit'] = 'Remote Connection LDAP/Radius: Edited configuration with LDAP';
$lang['report_0008_system_import_sync_disabled'] = 'Remote Connection LDAP/Radius: Disabled synchronization with LDAP';

$lang['report_0008_system_import_sync_convert_users'] = 'Remote Connection LDAP/Radius: Converted users to local';
$lang['report_0008_system_import_sync_convert_groups'] = 'Remote Connection LDAP/Radius: Converted groups to local';

$lang['report_0008_system_import_sync_remove_users'] = 'Remote Connection LDAP/Radius: Remove user connection LDAP \'%1$s\'';
$lang['report_0008_system_import_sync_remove_groups'] = 'Remote Connection LDAP/Radius: Remove group connection LDAP \'%1$s\'';

$lang['report_0008_openvpn_server_client_del'] = 'OpenVPN Client: Delete server \'%1$s (%2$s)\'';
$lang['report_0008_openvpn_server_client_disabled'] = 'OpenVPN Client: Disabled server \'%1$s (%2$s)\'';
$lang['report_0008_openvpn_server_client_enabled'] = 'OpenVPN Client: Enabled server \'%1$s (%2$s)\'';

$lang['report_0008_openvpn_server_client_edit'] = 'OpenVPN Client: Edited server \'%1$s (%2$s)\'';
$lang['report_0008_openvpn_server_client_new'] = 'OpenVPN Client: New server \'%1$s (%2$s)\'';
$lang['report_0008_openvpn_server_client_edit_dup'] = 'OpenVPN Client: Duplicate/Edited server \'%1$s (%2$s)\'';
$lang['report_0008_openvpn_server_client_new_dup'] = 'OpenVPN Client: Duplicate/New server \'%1$s (%2$s)\'';
$lang['report_0008_openvpn_server_client_dup'] = 'OpenVPN Client: Server duplicated from \'%1$s (%2$s)\' to \'%3$s (%4$s)\'';

$lang['report_0008_openvpn_server_csc_delete'] = 'OpenVPN CSC: Delete server \'%1$s (%2$s)\'';
$lang['report_0008_openvpn_server_csc_disabled'] = 'OpenVPN CSC: Disabled server \'%1$s (%2$s)\'';
$lang['report_0008_openvpn_server_csc_enabled'] = 'OpenVPN CSC: Enabled server \'%1$s (%2$s)\'';

$lang['report_0008_openvpn_server_csc_edit'] = 'OpenVPN CSC: Edited server \'%1$s (%2$s)\'';
$lang['report_0008_openvpn_server_csc_new'] = 'OpenVPN CSC: New server \'%1$s (%2$s)\'';
$lang['report_0008_openvpn_server_csc_edit_dup'] = 'OpenVPN CSC: Duplicate/Edited server \'%1$s (%2$s)\'';
$lang['report_0008_openvpn_server_csc_new_dup'] = 'OpenVPN CSC: Duplicate/New server \'%1$s (%2$s)\'';
$lang['report_0008_openvpn_server_csc_dup'] = 'OpenVPN CSC: Duplicate server from \'%1$s (%2$s)\' to \'%3$s (%4$s)\'';

$lang['report_0008_openvpn_server_del'] = 'OpenVPN: Delete server \'%1$s (%2$s)\'';
$lang['report_0008_openvpn_server_disabled'] = 'OpenVPN: Disabled server \'%1$s (%2$s)\'';
$lang['report_0008_openvpn_server_enabled'] = 'OpenVPN: Enabled server \'%1$s (%2$s)\'';

$lang['report_0008_openvpn_server_edit'] = 'OpenVPN: Edited server \'%1$s (%2$s)\'';
$lang['report_0008_openvpn_server_new'] = 'OpenVPN: New server \'%1$s (%2$s)\'';
$lang['report_0008_openvpn_server_edit_dup'] = 'OpenVPN: Duplicate/Edited server \'%1$s (%2$s)\'';
$lang['report_0008_openvpn_server_new_dup'] = 'OpenVPN: Duplicate/New server \'%1$s (%2$s)\'';
$lang['report_0008_openvpn_server_dup'] = 'OpenVPN: Duplicate server from \'%1$s (%2$s)\' to \'%3$s (%4$s)\'';
