<?php

//reports.php - controller
$lang['reports_generating'] = "Generating report";
$lang['reports_err_generating'] = "Could not generate report";
$lang['reports_success_removed'] = "Report removed successfully!";
$lang['reports_success_removed_all'] = "All Reports removed successfully!";
$lang['reports_confirm_all_files_remove'] = "Do you really want to delete all reports?";
$lang['reports_file_not_search'] = "There are no reviews for this product.";
$lang['reports_queue_success_remove'] = "Report removed of the queue successfully!";
$lang['reports_queue_error_remove'] = "Could not to remove the report of the queue!";
$lang['reports_provide_interv_from'] = "You must provide a Interval (From)";
$lang['reports_provide_interv_until'] = "You must provide a Interval (Until)";

//reports.php - view
$lang['reports_header'] = "Reports";
$lang['reports_pre_title'] = "Reports";
$lang['reports_title_sub1'] = "Summarized";
$lang['reports_title_sub2'] = "Detailed";
$lang['reports_input_filters'] = "Filters";
$lang['reports_input_period'] = "Period";
$lang['reports_input_registers'] = "Total records";
$lang['reports_input_ext'] = "Format";
$lang['reports_btn_process'] = "Process";
$lang['reports_btn_loading'] = "Loading ...";
$lang['reports_custom_title'] = "Data Export";
$lang['reports_input_interval'] = "Range";
$lang['reports_input_from'] = "From:";
$lang['reports_input_until'] = "To:";
$lang['reports_input_user'] = "User";
$lang['reports_input_ip'] = "IP";
$lang['reports_input_categories'] = "Categories";
$lang['reports_input_total_records'] = "Total Records";
$lang['reports_msg_limit'] = "The interval limit for 3 months query!";
$lang['reports_msg_select_rel'] = "Select Report!";
$lang['reports_zone'] = "Zone";

//reporta_files.php
$lang['reports_files_header'] = "Report List";
$lang['reports_files_date'] = "Date / Time";
$lang['reports_files_report'] = "Report";
$lang['reports_files_download'] = "Download";
$lang['reports_files_remove'] = "Remove File";
$lang['reports_all_files_remove'] = "Remove All Files";
$lang['reports_files_processing'] = "Processing";
$lang['reports_files_filesize'] = "Size (bytes)";

//reports_helper.php
$lang['reports_helpers_prel1'] = "TOP Users (MB Consumption)";
$lang['reports_helpers_prel2'] = "TOP Social Networks (Hits)";
$lang['reports_helpers_prel3'] = "TOP Categories (Hits)";
$lang['reports_helpers_prel4'] = "TOP Domains (MB Consumption)";
$lang['reports_helpers_prel5'] = "TOP Sites";
$lang['reports_helpers_prel6'] = "TOP VPN Users (Connection Time)";
$lang['reports_helpers_prel7'] = "Facebook Access TOPs";
$lang['reports_helpers_prel8'] = "TOP Youtube Access";
$lang['reports_helpers_prel9'] = "TOP Access Instagram";
$lang['reports_helpers_prel10'] = "TOP Accesses Linkedin";
$lang['reports_helpers_crel1'] = "User Access";
$lang['reports_helpers_crel2'] = "Access by IP Address";
$lang['reports_helpers_crel3'] = "VPN connection time";
$lang['reports_helpers_crel4'] = "Captive Portal/Audit";
$lang['reports_helpers_crel5'] = "Top Accessed Domains";
$lang['reports_helpers_crel6'] = "WebFilter Justifications";
$lang['reports_helpers_crel7'] = "Detailed VPN Connection Time";
$lang['reports_helpers_erel1'] = "User Access (Analytic)";
$lang['reports_helpers_erel2'] = "IP Address Access (Analytical)";
$lang['reports_helpers_erel3'] = "Access per Users Group";
$lang['reports_helpers_recent'] = "Recent";
$lang['reports_helpers_7days'] = "7 days";
$lang['reports_helpers_30days'] = "30 days";

//ReportsCommandLine.php
$lang['reports_cmd_err1'] = "Could not execute command:";
$lang['reports_cmd_err2'] = "The process PID could not be set!";
$lang['reports_cmd_err3'] = "Could not create process PID!";
$lang['reports_cmd_err4'] = "Could not get report data!";
$lang['reports_cmd_footer'] = "Generated by BluePex DataClick | {PAGENO} of {nb}";
$lang['reports_cmd_consumer'] = "Total Consumed (MB)";
$lang['reports_cmd_access'] = "Total Accessed";
$lang['reports_cmd_categ'] = "Categories";
$lang['reports_cmd_ip'] = "IP Address";
$lang['reports_cmd_username'] = "Username";
$lang['reports_cmd_zone'] = "Zone";
$lang['reports_cmd_mac'] = "MAC Address";
$lang['reports_cmd_beg_connect'] = "Connection Started In";
$lang['reports_cmd_last_active'] = "Last Activity";
$lang['reports_cmd_disp'] = "Device";
$lang['reports_cmd_rem_ip'] = "Remote IP Address";
$lang['reports_cmd_domain'] = "Domain";
$lang['reports_cmd_connect_time'] = "Connection Time";
$lang['reports_cmd_port'] = "Port";
$lang['reports_cmd_bytes_send'] = "Bytes Sent";
$lang['reports_cmd_bytes_rec'] = "Bytes Received";
$lang['reports_cmd_yes'] = "Yes";
$lang['reports_cmd_no'] = "No";
$lang['reports_cmd_blocked'] = "Locked";
$lang['reports_cmd_local_ip'] = "Local IP Address";
$lang['reports_cmd_group'] = "Group";
$lang['reports_cmd_date'] = "Date / Time";
$lang['reports_cmd_default_utm'] = "The UTM pattern does not exist!";
$lang['reports_cmd_time_connect'] = "Connection";
$lang['reports_cmd_time_disconnect'] = "Disconnection";

//000x.php
$lang['reports_c_period'] = "Period (of):";
$lang['reports_c_period_until'] = "Period (to):";
$lang['reports_c_user'] = "User:";
$lang['reports_c_ip'] = "IP:";
$lang['reports_c_address'] = "Address:";
$lang['reports_c_user'] = "User";
$lang['reports_c_group'] = "Group / Cost Center";
$lang['reports_c_access'] = "Access Qty";
$lang['reports_c_consumer'] = "Consumption (MB)";
$lang['reports_c_totalmb'] = "Total (MB):";
$lang['reports_c_date'] = "Date / Time";
$lang['reports_c_categ'] = "Categories";
$lang['reports_c_access_time'] = "Access time (sec)";
$lang['reports_c_remote_ip'] = "IP Remote";
$lang['reports_c_local_ip'] = "Local IP";
$lang['reports_c_port'] = "Port";
$lang['reports_c_bytes_send'] = "Sent Data (bytes)";
$lang['reports_c_bytes_rec'] = "Data Received (bytes)";
$lang['reports_c_temp'] = "time";
$lang['reports_c_mac'] = "MAC Address";
$lang['reports_c_begin_activities'] = "Connection Started In";
$lang['reports_c_last_activities'] = "Last Activity";
$lang['reports_c_disp'] = "Device";
$lang['reports_c_rejected'] = "Rejected";
$lang['reports_c_justification'] = "Justification";
$lang['reports_c_source'] = "Source";
$lang['reports_c_name'] = "Name";
$lang['reports_c_last_name'] = "Last Name";
$lang['reports_c_birthday'] = "Birthday";
$lang['reports_c_form1'] = "Form 1";
$lang['reports_c_form2'] = "Form 2";
$lang['reports_c_time_connect'] = "Connection";
$lang['reports_c_time_disconnect'] = "Disconnection";

//P000x.php
$lang['reports_p_period'] = "Period (of):";
$lang['reports_p_interval_of'] = "Range (of):";
$lang['reports_p_interval_until'] = "Range (to):";
$lang['reports_p_utm'] = "UTM:";
$lang['reports_p_address'] = "Address:";
$lang['reports_p_user'] = "User";
$lang['reports_p_consumer'] = "Consumption (MB)";
$lang['reports_p_access'] = "Access Qty";
$lang['reports_p_domain'] = "Domain";
$lang['reports_p_consumer'] = "Consumption (MB)";
$lang['reports_p_totalmb'] = "Total (MB):";
$lang['reports_p_connect_time'] = "Connection time (ms)";
$lang['reports_p_ip'] = "IP Address:";
